### PR TITLE
.

### PR DESCRIPTION
**Pull request by Starwarslover1998**

### CODE REVIEW

**Comment by Starwarslover1998** [comment]
.

**Comment by Starwarslover1998** [comment]
.

**Comment by Starwarslover1998** [comment]
.

**Comment by Starwarslover1998** [comment]
.

**Comment by MrLamont-HHSS** [comment]
Q2: There is more to do in the trace. Bubble sort doesn't know it is finished until it does a COMPLETE pass of the array without swapping any numbers.
Q4: Not a very detailed explanation. You need to expand on why you think the swapping of Insertion Sort would be better than the checking of Selection sort. Selection finds the correct number for each spot and never returns to that one once it finds its answer.

You have only submitted the 1st programming exercise. Where are the other 2? Also, you have no comments in that file.

**Pull request closed without merging**
